# Generated by Django 4.1.3 on 2022-12-24 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('department_id', models.SmallIntegerField()),
                ('employee_firstname', models.CharField(max_length=10)),
                ('employee_lastname', models.CharField(max_length=10)),
                ('position_id', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=15)),
                ('process_time', models.DateTimeField()),
                ('employee_id', models.SmallIntegerField()),
                ('process_type_id', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=10)),
            ],
        ),
    ]
