# Generated by Django 4.1.3 on 2022-12-24 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichiworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='employee_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 24, 20, 26, 8, 60620)),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_type_id',
            field=models.SmallIntegerField(default=1),
        ),
    ]
