# Generated by Django 4.1.3 on 2022-12-27 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichiworks', '0003_message_alter_process_process_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='process_type_id',
            new_name='status_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 20, 52, 53, 918041)),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 20, 52, 53, 916703)),
        ),
    ]
