# Generated by Django 4.1.3 on 2023-02-10 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichiworks', '0008_remove_message_process_id_alter_message_message_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='order_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 19, 41, 18, 963296)),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 19, 41, 18, 961772)),
        ),
    ]
