# Generated by Django 4.1.3 on 2023-02-10 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichiworks', '0009_message_order_number_alter_message_message_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='employee_id_from',
            field=models.SmallIntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='message',
            name='employee_id_to',
            field=models.SmallIntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 19, 59, 47, 168173)),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 19, 59, 47, 166843)),
        ),
    ]
