# Generated by Django 4.1.3 on 2022-12-16 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySetting',
            fields=[
                ('setting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_id', models.SmallIntegerField()),
                ('destination_id', models.SmallIntegerField()),
                ('distoribution_type_id', models.SmallIntegerField()),
                ('folding', models.BooleanField()),
                ('notes', models.TextField()),
                ('arrive_offset', models.CharField(max_length=5)),
                ('shipp_offset', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('destination_name', models.CharField(max_length=100)),
                ('destination_post', models.CharField(max_length=20)),
                ('destination_address', models.CharField(max_length=100)),
                ('destination_tell', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DistoributionType',
            fields=[
                ('distribution_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('distribution_type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('printer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('printer_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_no', models.CharField(max_length=5)),
                ('service_size', models.CharField(max_length=5)),
                ('service_tieup', models.BooleanField()),
                ('service_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=10)),
                ('shopHoliday_id', models.SmallIntegerField()),
                ('shop_tell', models.CharField(max_length=30)),
                ('shop_fax', models.CharField(max_length=30)),
                ('shop_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopHoliday',
            fields=[
                ('shopHoliday_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('shopHoliday_name', models.CharField(max_length=10)),
            ],
        ),
    ]
