# Generated by Django 4.1.3 on 2022-12-20 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rbworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSample',
            fields=[
                ('shopsample_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_id', models.SmallIntegerField()),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('service_id', models.UUIDField()),
                ('shopsample_number', models.SmallIntegerField()),
            ],
        ),
    ]
